# Generated by Django 4.1.3 on 2023-01-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_usermodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productapp.usermodel')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
    ]
