# Generated by Django 4.1.3 on 2023-01-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0013_alter_recommendation_product_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recommendation',
            table=None,
        ),
    ]
