# Generated by Django 4.1.3 on 2023-01-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0015_alter_recommendation_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
    ]
