# Generated by Django 4.1.3 on 2023-01-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0016_remove_recommendation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
