# Generated by Django 4.1.3 on 2023-01-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0020_alter_product_id_alter_usermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='shape',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
