# Generated by Django 4.1.3 on 2023-01-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0021_recommendation_name_recommendation_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='shape',
        ),
    ]
