# Generated by Django 4.1.3 on 2023-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0022_remove_recommendation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(),
        ),
    ]
